# Generated by Django 3.2.5 on 2022-10-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profimg',
            field=models.ImageField(default='generic-profile_0.png', upload_to='profile_images'),
        ),
    ]
