# Generated by Django 3.2.5 on 2022-10-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0004_post_profimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='profimg',
            field=models.ImageField(upload_to='profile_images'),
        ),
    ]
